chore: see format output

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -41,7 +41,15 @@ jobs:
         working-directory: packages/clerk_backend_api
 
       - name: Verify formatting of clerk_flutter
-        run: dart format --line-length=80 --output=none --set-exit-if-changed .
+        shell: bash
+        run: |
+          set +e
+          dart format --line-length=80 --set-exit-if-changed .
+          if [[ $? -ne 0 ]]; then
+            echo "Formatting failed:"
+            git diff
+            exit 1
+          fi
         working-directory: packages/clerk_flutter
 
       - name: Analyze clerk_auth
